name: CICD Database Dev to Prod

on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CI/CD Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH Connect to Database Server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "âœ… Berhasil konek ke server"

            cd /home/cicd
            docker compose up -d
            echo "âœ… Berhasil menjalankan docker-compose up -d"

            # CI (Continuous Integration)
            echo "â³ Menunggu Server MySQL siap"
            sleep 30

            docker exec mysql_devel_container mysql -u root -pTelkom123! -e "SHOW DATABASES;"
            echo "âœ… Berhasil menampilkan database di mysql_devel_container"

            # CD (Continuous Deployment)
            echo "ðŸ“¦ Dump database dari mysql_devel_container"
            docker exec mysql_devel_container sh -c 'mysqldump -u root -pTelkom123! academics_devel' > /tmp/dump_devel.sql

            echo "ðŸ“‚ Copy dump ke mysql_prod_container"
            docker cp /tmp/dump_devel.sql mysql_prod_container:/tap/dump_devel.sql

            echo "ðŸ“¥ Import dump ke mysql_prod_container"
            docker exec -i mysql_prod_container sh -c 'mysql -u root -pTelkom123! academics < /tap/dump_devel.sql'

            echo "âœ… Berhasil mengimpor database ke mysql_prod_container"
